CREATE DATABASE mt2_data;
CREATE DATABASE mt2_reports;
CREATE DATABASE mt2_shuttle;
CREATE DATABASE mt2_tmp_tables;
CREATE DATABASE attribution;
CREATE DATABASE dima_data;
CREATE DATABASE list_profile;
CREATE DATABASE list_profile_export_tables;
CREATE DATABASE suppression;
GRANT ALL PRIVILEGES ON *.* TO 'homestead'@'localhost' IDENTIFIED BY 'secret';
