-
    frontend_feature_id: 1
    permission_id: 1
-
    frontend_feature_id: 1
    permission_id: 7
-
    frontend_feature_id: 1
    permission_id: 8
-
    frontend_feature_id: 1
    permission_id: 9
-
    frontend_feature_id: 1
    permission_id: 10
-
    frontend_feature_id: 1
    permission_id: 11
-
    frontend_feature_id: 1
    permission_id: 12
-
    frontend_feature_id: 2
    permission_id: 2
-
    frontend_feature_id: 2
    permission_id: 3
-
    frontend_feature_id: 2
    permission_id: 4
-
    frontend_feature_id: 2
    permission_id: 5
-
    frontend_feature_id: 2
    permission_id: 6
-
    frontend_feature_id: 3
    permission_id: 22
-
    frontend_feature_id: 3
    permission_id: 23
-
    frontend_feature_id: 3
    permission_id: 24
-
    frontend_feature_id: 3
    permission_id: 38
-
    frontend_feature_id: 3
    permission_id: 39
-
    frontend_feature_id: 3
    permission_id: 40
-
    frontend_feature_id: 3
    permission_id: 78
-
    frontend_feature_id: 3
    permission_id: 79
-
    frontend_feature_id: 3
    permission_id: 80
-
    frontend_feature_id: 3
    permission_id: 81
-
    frontend_feature_id: 3
    permission_id: 82
-
    frontend_feature_id: 3
    permission_id: 101
-
    frontend_feature_id: 3
    permission_id: 102
-
    frontend_feature_id: 3
    permission_id: 103
-
    frontend_feature_id: 3
    permission_id: 104
-
    frontend_feature_id: 3
    permission_id: 105
-
    frontend_feature_id: 3
    permission_id: 106
-
    frontend_feature_id: 3
    permission_id: 107
-
    frontend_feature_id: 3
    permission_id: 282
-
    frontend_feature_id: 3
    permission_id: 283
-
    frontend_feature_id: 3
    permission_id: 284
-
    frontend_feature_id: 3
    permission_id: 285
-
    frontend_feature_id: 3
    permission_id: 341
-
    frontend_feature_id: 3
    permission_id: 342
-
    frontend_feature_id: 3
    permission_id: 343
-
    frontend_feature_id: 3
    permission_id: 344
-
    frontend_feature_id: 3
    permission_id: 345
-
    frontend_feature_id: 3
    permission_id: 346
-
    frontend_feature_id: 3
    permission_id: 347
-
    frontend_feature_id: 3
    permission_id: 348
-
    frontend_feature_id: 3
    permission_id: 349
-
    frontend_feature_id: 4
    permission_id: 13
-
    frontend_feature_id: 4
    permission_id:
-
    frontend_feature_id: 4
    permission_id:
-
    frontend_feature_id: 4
    permission_id:
-
    frontend_feature_id: 4
    permission_id:
-
    frontend_feature_id:
    permission_id:
