create table advertiser_signup
(
	advertiser_id	int(11) not null auto_increment primary key,
	date_added	datetime not null,
	first_name	varchar(50) not null,
	last_name	varchar(50) not null,
	title	varchar(50) not null,
	co_name	varchar(50) not null,
	address1	varchar(100) not null,
	address2	varchar(100),
	city	varchar(50) not null,
	state	char(2) not null,
	zip		varchar(10) not null,
	phone	varchar(12) not null,
	fax		varchar(12) not null,
	email	varchar(100) not null,
	web		varchar(100) not null,
	subsidiary	char,
	sub_name	varchar(50),
	traded	char,
	empsize	varchar(4),
	otherurls	longblob,
	timeonweb	varchar(20),
	bus_desc	longblob,
	target_market	varchar(10),
	run_aff_prog	char,	
	email_adv	char,
	ml_pub	char,
	ad_budget	varchar(20),
	ad_budget_12	varchar(20),
	percent_budget	varchar(10),
	ml_hear	varchar(50),
	comments	longblob
);
