vi 3rdparty_deploy_it.cgi
vi 3rdparty_schedule_copy_save.cgi
vi advertiser_setup_save.cgi
vi camp_replace_save.cgi
vi camp_save.cgi
vi camp_step5_save.cgi
vi category_trigger_save.cgi
vi dosmonos_deploy_it.cgi
vi save_newsletter_schedule.cgi
vi save_schedule.cgi
vi schedule_copy_save.cgi
vi upd_newsletter.cgi
