./remove_domain.pl aglaws.com
./remove_domain.pl basjlaw.com
./remove_domain.pl bhmklaw.com
./remove_domain.pl bnm-law.com
./remove_domain.pl bnwlaw.com
./remove_domain.pl bscr-law.com
./remove_domain.pl burgumlaw.com
./remove_domain.pl cameroncountylawyer.com
./remove_domain.pl cothranlawoffice.com
./remove_domain.pl criteslawfirm.com
./remove_domain.pl degenhartlaw.com
./remove_domain.pl dohertylawoffices.net
./remove_domain.pl eichhornlaw.com
./remove_domain.pl fredrickslaw.com
./remove_domain.pl gibbonslaw.com
./remove_domain.pl grossmanlaw.net
./remove_domain.pl hamdamlaw.com
./remove_domain.pl hfklaw.com
./remove_domain.pl kts-law.com
./remove_domain.pl lawlords.net
./remove_domain.pl lawtx.com
./remove_domain.pl leatherburylawoffice.com
./remove_domain.pl mhcilaw.com
./remove_domain.pl mlrlawyers.com
./remove_domain.pl nwlawoffice.com
./remove_domain.pl ohlylaw.com
./remove_domain.pl platzerlaw.com
./remove_domain.pl rirealestatelaw.com
./remove_domain.pl rkkdlaw.com
./remove_domain.pl rmcolaw.com
./remove_domain.pl roberttribblelaw.com
./remove_domain.pl tallmanlaw.com
./remove_domain.pl tamakilaw.com
./remove_domain.pl theallisonlawfirm.com
./remove_domain.pl tiftonlaw.com
./remove_domain.pl tnelaw.com
