./remove_domain.pl tuyomail.com
./remove_domain.pl message.alltel.com
./remove_domain.pl ipnpaging.com
./remove_domain.pl mycricket.com
./remove_domain.pl page-us.com
./remove_domain.pl qwtext.com
./remove_domain.pl awsms.com
./remove_domain.pl epageme.com
./remove_domain.pl imcingular.com
./remove_domain.pl myawi.com
./remove_domain.pl guamcell.com
./remove_domain.pl advmms.com
./remove_domain.pl agw-atl.pdg.bellsouth.net
./remove_domain.pl airlinkmobile.com
./remove_domain.pl airmessage.net
./remove_domain.pl airpage.net
./remove_domain.pl alaskadigitel.com
./remove_domain.pl archwireless.net
./remove_domain.pl atlmmg1.glr.cingular.net
./remove_domain.pl attmobility.com
./remove_domain.pl attmobility.net
./remove_domain.pl bellsouthtms.com
./remove_domain.pl bellsouthtms.net
./remove_domain.pl bellsouthwirelessemail.com
./remove_domain.pl bellsouthwirelessemail.net
./remove_domain.pl blswe.com
./remove_domain.pl blswe.net
./remove_domain.pl breweloquiwireless.net
./remove_domain.pl c1usa.com
./remove_domain.pl c1wi.com
./remove_domain.pl calnorth.net
./remove_domain.pl cell1net.net
./remove_domain.pl cell1wv.net
./remove_domain.pl cellcompage.com
./remove_domain.pl cellcomsms.com
./remove_domain.pl cellonemail.com
./remove_domain.pl cellular.ameritech.com
./remove_domain.pl cellular1.net
./remove_domain.pl cellularone.blackberry.net
./remove_domain.pl centennialcom.com
./remove_domain.pl centennialwireless.com
./remove_domain.pl cingularme.com
./remove_domain.pl cingularme.net
./remove_domain.pl cingularme.us
./remove_domain.pl clearlydigital.com
./remove_domain.pl clearpath.acswireless.com
./remove_domain.pl cookmail.com
./remove_domain.pl corrcomm.com
./remove_domain.pl corrwireless.com
./remove_domain.pl corrwireless.net
./remove_domain.pl csouth1.com
./remove_domain.pl csouth1.net
./remove_domain.pl cwemail.com
./remove_domain.pl cwemail.net
./remove_domain.pl cwmail2.glr.cingular.com
./remove_domain.pl cwwsms.com
./remove_domain.pl dcswi.com
./remove_domain.pl digitaledge.acswireless.com
./remove_domain.pl edgehiptop.com
./remove_domain.pl edgehiptopmail.com
./remove_domain.pl edgemobile.net
./remove_domain.pl edgesend.com
./remove_domain.pl edgesend.net
./remove_domain.pl edgewireless.com
./remove_domain.pl eloqui.net
./remove_domain.pl email.swbw.com
./remove_domain.pl email.uscc.net
./remove_domain.pl epage.lrps.com
./remove_domain.pl firstcellular.net
./remove_domain.pl glr.sbms.sbc.com
./remove_domain.pl gocbw.com
./remove_domain.pl gwteletech.com
./remove_domain.pl hiptop.suncom.net
./remove_domain.pl info2go.com
./remove_domain.pl ivcdata.com
./remove_domain.pl ivcel.net
./remove_domain.pl ivctext.com
./remove_domain.pl iwarn.com
./remove_domain.pl iwspcs.com
./remove_domain.pl iwspcs.net
./remove_domain.pl leaco.net
./remove_domain.pl leaco.org
./remove_domain.pl mail.data1source.com
./remove_domain.pl mail.pagespringfield.com
./remove_domain.pl mail.westlinkcom.com
./remove_domain.pl messaging.nextel.com
./remove_domain.pl messaging.sprintpcs.com
./remove_domain.pl mid-texcellular.com
./remove_domain.pl midwestwireless.net
./remove_domain.pl minncommpaging.com
./remove_domain.pl mmode.com
./remove_domain.pl mms.dobson.net
./remove_domain.pl mms.farmerswireless.com
./remove_domain.pl mms.suncom.net
./remove_domain.pl mms.uscc.net
./remove_domain.pl mms.westlinkcom.com
./remove_domain.pl mmseloquiwireless.net
./remove_domain.pl mobilcom.net
./remove_domain.pl mobile.att.net
./remove_domain.pl mobile.c1-slo.com
./remove_domain.pl mobile.celloneusa.com
./remove_domain.pl mobile.cellularone-slo.com
./remove_domain.pl mobile.cellularoneslo.com
./remove_domain.pl mobile.centralcoastdata.com
./remove_domain.pl mobile.dobson.net
./remove_domain.pl mobile.dobsoncellular.com
./remove_domain.pl mobile.fivestarwireless.com
./remove_domain.pl mobilecomm.net
./remove_domain.pl mohavewireless.com
./remove_domain.pl mpot.com
./remove_domain.pl my2way.com
./remove_domain.pl myblue.com
./remove_domain.pl myboostmobile.com
./remove_domain.pl myc29.net
./remove_domain.pl mycellone.net
./remove_domain.pl mycellonephone.com
./remove_domain.pl mycingular.com
./remove_domain.pl mycingular.net
./remove_domain.pl mydcs1.com
./remove_domain.pl mylyrix.net
./remove_domain.pl mymetropcs.com
./remove_domain.pl mymmode.com
./remove_domain.pl mymmsmail.com
./remove_domain.pl omnicom-paging.com
./remove_domain.pl onelinkpcs.com
./remove_domain.pl pacbellpcs.net
./remove_domain.pl page-all.com
./remove_domain.pl page.mobilfone.com
./remove_domain.pl page.nextel.com
./remove_domain.pl pageallcom.com
./remove_domain.pl pageme.teletouch.com
./remove_domain.pl pageme.teletouch.net
./remove_domain.pl pagenet.net
./remove_domain.pl pagerpeople.com
./remove_domain.pl paging.acswireless.com
./remove_domain.pl paging.mobilfone.com
./remove_domain.pl paging.sbc.com
./remove_domain.pl paging.telebeep.com
./remove_domain.pl pics.cellcom.com
./remove_domain.pl pim.infospace.com
./remove_domain.pl pioneerenidcellular.com
./remove_domain.pl pix.cellularsouth.com
./remove_domain.pl prestopaging.com
./remove_domain.pl quiktxt.com
./remove_domain.pl qwestmessagepack.com
./remove_domain.pl qwestmessagepak.com
./remove_domain.pl qwestmp.com
./remove_domain.pl racomm.com
./remove_domain.pl radiocommpaging.com
./remove_domain.pl radiocontrolit.com
./remove_domain.pl radiopaging.com
./remove_domain.pl rccpaging.com
./remove_domain.pl redicall.com
./remove_domain.pl satellink.net
./remove_domain.pl sbc2way.com
./remove_domain.pl sbcemail.com
./remove_domain.pl sbcpaging.com
./remove_domain.pl sbycomm.com
./remove_domain.pl sccvmail.com
./remove_domain.pl simmetrypcs.com
./remove_domain.pl simmetrypcs.net
./remove_domain.pl sms-bscc.bellsouth.com
./remove_domain.pl sms.bellsouth.com
./remove_domain.pl sms.cleartalk.net
./remove_domain.pl sms.corrwireless.com
./remove_domain.pl sms.cvalley.net
./remove_domain.pl sms.farmerswireless.com
./remove_domain.pl sms.petrocom.net
./remove_domain.pl sms.snakeriverpcs.com
./remove_domain.pl smseloquiwireless.net
./remove_domain.pl southernlinc.com
./remove_domain.pl srtwireless.com
./remove_domain.pl stenocall.com
./remove_domain.pl suncom.blackberry.net
./remove_domain.pl text.simplefreedom.net
./remove_domain.pl tmomail.net
./remove_domain.pl tms.bellsouth.com
./remove_domain.pl tms.suncom.com
./remove_domain.pl ubetwireless.com
./remove_domain.pl usamobility.net
./remove_domain.pl uscc.textmsg.com
./remove_domain.pl utext.com
./remove_domain.pl viaeromail.com
./remove_domain.pl viaeromms.com
./remove_domain.pl viaerosms.com
./remove_domain.pl vtext.com
./remove_domain.pl wireless.bellsouth.com
./remove_domain.pl wwtext.net
./remove_domain.pl zsend.com
